### ISSUE TITLE
Bluefruit Library

### ISSUE THREAD

**Issue by msportillo** [adafruit/Bluefruit_LE_Connect#27]
Hi,
I already downloaded the entire project but I need to create my own project from scratch. Is there a folder with all the files that I need to import in my project?
Thank you.

**Comment by galileomd** [comment]
second this request!

**Comment by Nikolai1024** [comment]
Yes. This is very complete and very cool but maybe a simpler example for beginners and list of requirements would be great.

**Comment by jayjayesh** [comment]
Please write steps how to implement this project in my project , if any one have successful to implement ?  thanks in advance.

**Comment by jayjayesh** [comment]
is this right way to implement this project ? 
http://recordit.co/0gQiCSEREF

**Comment by JeanRintoul** [comment]
Yes this would be very helpful. I am having trouble compiling the workspace as it seems to have lots of other dependencies that aren't core to the project. Any help, or a simple instructions on how to integrate the bluetooth part would be much appreciated(not looking for the watchkit parts).

**Comment by microbuilder** [comment]
Sorry, we're unlikely to publish a separate absolute bare bones reference application for this since mobile development is way outside the scope of our core competencies and educational mission.  We publish the source for our own apps as a free to use reference, but that's probably the best we can offer at this point, and the source is delivered entirely as-is and unsupported.

Our goal with this project is simply to have reliable mobile apps that can talk to our Bluefruit hardware products, and we're happy to publish the source code when we can, but there are way more companies and communities out there teaching mobile development, and we need to dedicate our limited resources to the things we do best, which is hardware and firmware.
