### ISSUE TITLE
Need upgrade to Swift 3.0!

### ISSUE THREAD

**Issue by tomasero** [adafruit/Bluefruit_LE_Connect#29]
I've been trying to port the app to Swift 3.0 with no success. Is this planned to be done anytime soon?

**Comment by microbuilder** [comment]
There are no immediate plans to update this app.  We recently published an update to it, and it will likely be several months before a new update gets pushed out, at which time we'll weigh the pros and cons of any update(s) ... but currently, the app will remain as is since we have to balance development here with several other mobile apps and projects.
