### ISSUE TITLE
Q: Are rx/tx characteristics guarantied to be provided for nRF8001-board?

### ISSUE THREAD

**Issue by 4ntoine** [adafruit/Bluefruit_LE_Connect#9]
Hi, I've read https://learn.adafruit.com/getting-started-with-the-nrf8001-bluefruit-le-breakout/adding-app-support

```
UART Service UUID: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
TX Characteristic UUID: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
RX Characteristic UUID: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
```

Does it mean you've created custom BLE service with custom characteristics and the firmware is uploaded to your nRF8001 boards that are in stock (https://www.adafruit.com/products/1697)?

Is it nRF8001-specific service (and developed not by Adafruti) or it's created and uploaded by Adafruit?
I'm going to purchase that board and use for my iOS app. 

One more question (not sure it's for your but for hardware engineer likely but probably you can know the answer):
I can't see Rx/Tx pin at https://www.adafruit.com/images/970x728/1697-04.jpg, so how can i wire it to my Arduino serial Rx/Tx pins?

**Comment by microbuilder** [comment]
Can you please post this up in the Adafruit support forums since that's the right place for this? The support staff generally don't monitor the Github issues or receive the email alerts here.  

But yes those are custom services that are defined by Nordic (i.e. not officially adopted services/chars accepted by the Bluetooth SIG), and are optional and are generated with the Software the accompanies the nRF8001 on Arduino (etc.).  These services don't exist in the 8001 itself ... no services do ... you always have to put your service definitions onto the 8001 via config information in SW at startup.

**Comment by 4ntoine** [comment]
Thanks for the reply, sorry about posting in wrong place.
